spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:9306/ad_service_dev?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Rdis2fun!

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    reactor:
      netty:
        http:
          client: DEBUG
    cn:
      lcola: DEBUG
